name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: featureflags
          POSTGRES_USER: ff
          POSTGRES_PASSWORD: ffpass
        ports: [5432:5432]
        options: >-
          --health-cmd :pg_isready -U ff" --health-intervals 5s
          --health-timeout 5s --health-retrier 5
      redis:
        image: redis:7-alpine
        ports: [6379:6379]

    env:
      DJANGO_ENV: local
      DJANGO_SECRET_KEY: ci-secret
      POSTGRES_DB: featureflags
      POSTGRES_USER: ff
      POSTGRES_PASSWORD: ffpass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_URL: redis://localhost:6379/0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit pytest

      - name: Lint & format
        run: pre-commit run --all-files --show-diff-on-failure

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run tests
        run: pytest -q

      - name: Build docker image
        run: docker build . -t featureflags:${{ github.sha }}

